# Generated by Django 5.2.17 on 2026-08-29 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name': 'Equipe',
                'verbose_name_plural': 'Equipes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='FamiliaSinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('nome', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Família de sinal',
                'verbose_name_plural': 'Famílias de sinal',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ItemConfiguracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'verbose_name': 'Item de configuração',
                'verbose_name_plural': 'Itens de configuração',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='MetricaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('dimensao', models.CharField(choices=[('global', 'Global'), ('produto', 'Produto'), ('equipe', 'Equipe'), ('familia', 'Família de sinal'), ('categoria', 'Categoria')], max_length=20)),
                ('chave', models.CharField(blank=True, max_length=80)),
                ('total', models.IntegerField(default=0)),
                ('total_kpi', models.IntegerField(default=0)),
                ('violacoes', models.IntegerField(default=0)),
                ('criticos', models.IntegerField(default=0)),
                ('resolvidos', models.IntegerField(default=0)),
                ('soma_mttr_seg', models.BigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Métrica diária',
                'verbose_name_plural': 'Métricas diárias',
                'ordering': ['-data'],
                'indexes': [models.Index(fields=['dimensao', 'chave', '-data'], name='core_metric_dimensa_76c36d_idx'), models.Index(fields=['-data'], name='core_metric_data_09e944_idx')],
                'unique_together': {('data', 'dimensao', 'chave')},
            },
        ),
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('prioridade', models.IntegerField(choices=[(1, '1 — Crítica'), (2, '2 — Alta'), (3, '3 — Média'), (4, '4 — Baixa'), (5, '5 — Muito Baixa')])),
                ('categoria', models.CharField(blank=True, max_length=40)),
                ('subcategoria', models.CharField(blank=True, max_length=40)),
                ('descricao', models.TextField()),
                ('aberto_em', models.DateTimeField()),
                ('resolvido_em', models.DateTimeField(blank=True, null=True)),
                ('encerrado_em', models.DateTimeField(blank=True, null=True)),
                ('duracao_seg', models.BigIntegerField(default=0, help_text='Campo `Duração` do dataset — tempo até resolução/encerramento.')),
                ('cod_fechamento', models.CharField(blank=True, max_length=80)),
                ('solucao', models.CharField(blank=True, choices=[('contorno', 'Contorno'), ('definitiva', 'Definitiva')], max_length=20)),
                ('aberto_por', models.CharField(choices=[('manual', 'Manual'), ('monitoramento', 'Monitoramento')], max_length=20)),
                ('status', models.CharField(choices=[('encerrado', 'Encerrado'), ('encerrado_auto', 'Encerrado Automaticamente'), ('sem_intervencao', 'Sem Intervenção'), ('aguardando', 'Aguardando Problema'), ('aberto', 'Aberto')], max_length=20)),
                ('entrou_kpi', models.BooleanField(default=False)),
                ('kpi_violado', models.BooleanField(blank=True, null=True)),
                ('origem', models.CharField(choices=[('dataset', 'Dataset Locaweb'), ('simulacao', 'Simulação manual')], default='dataset', max_length=20)),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidentes', to='core.equipe')),
                ('familia_sinal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidentes', to='core.familiasinal')),
                ('incidente_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filhos', to='core.incidente')),
                ('item_configuracao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidentes', to='core.itemconfiguracao')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidentes', to='core.produto')),
            ],
            options={
                'verbose_name': 'Incidente',
                'verbose_name_plural': 'Incidentes',
                'ordering': ['-aberto_em'],
                'indexes': [models.Index(fields=['-aberto_em'], name='core_incide_aberto__abaf04_idx'), models.Index(fields=['entrou_kpi', '-aberto_em'], name='core_incide_entrou__8e25ce_idx'), models.Index(fields=['produto', '-aberto_em'], name='core_incide_produto_906486_idx'), models.Index(fields=['equipe', '-aberto_em'], name='core_incide_equipe__677081_idx'), models.Index(fields=['familia_sinal', '-aberto_em'], name='core_incide_familia_270bf4_idx'), models.Index(fields=['kpi_violado'], name='core_incide_kpi_vio_6a9111_idx')],
            },
        ),
    ]
