# Generated by Django 5.2.17 on 2026-08-30 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='incidente',
            index=models.Index(fields=['item_configuracao', 'aberto_em'], name='core_incide_item_co_38bf19_idx'),
        ),
    ]
