# Generated by Django 5.2.17 on 2026-09-11 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrevisaoRegistrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=40)),
                ('algoritmo', models.CharField(blank=True, max_length=40)),
                ('dimensao', models.CharField(default='global', max_length=20)),
                ('chave', models.CharField(blank=True, max_length=80)),
                ('data_execucao', models.DateField(help_text='Último dia observado quando a previsão foi feita.')),
                ('data_alvo', models.DateField()),
                ('horizonte', models.IntegerField()),
                ('valor_previsto', models.FloatField()),
                ('minimo', models.FloatField(blank=True, null=True)),
                ('maximo', models.FloatField(blank=True, null=True)),
                ('valor_real', models.FloatField(blank=True, null=True)),
                ('origem', models.CharField(choices=[('backtest', 'Teste fora da amostra'), ('producao', 'Previsão publicada')], default='producao', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Previsão registrada',
                'verbose_name_plural': 'Previsões registradas',
                'ordering': ['-data_alvo', 'modelo', 'dimensao', 'chave'],
                'indexes': [models.Index(fields=['modelo', '-data_alvo'], name='ml_previsao_modelo_04aa2a_idx'), models.Index(fields=['dimensao', 'chave', '-data_alvo'], name='ml_previsao_dimensa_ee6257_idx')],
                'constraints': [models.UniqueConstraint(fields=('modelo', 'dimensao', 'chave', 'data_execucao', 'data_alvo'), name='previsao_unica_por_execucao')],
            },
        ),
    ]
